In [ ]:
def convert_length(value, unit):
    """
    Convert length between meters and feet.
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('m' for meters, 'ft' for feet).
    :return: The converted value with the appropriate unit.
    """
    if unit == "m":
        return value * 3.28084, "ft"
    elif unit == "ft":
        return value / 3.28084, "m"
    else:
        raise ValueError("Unsupported length unit")

def convert_weight(value, unit):
    """
    Convert weight between kilograms and pounds.
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('kg' for kilograms, 'lbs' for pounds).
    :return: The converted value with the appropriate unit.
    """
    if unit == "kg":
        return value * 2.20462, "lbs"
    elif unit == "lbs":
        return value / 2.20462, "kg"
    else:
        raise ValueError("Unsupported weight unit")

def convert_volume(value, unit):
    """
    Convert volume between liters and gallons.
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('L' for liters, 'gal' for gallons).
    :return: The converted value with the appropriate unit.
    """
    if unit == "L":
        return value * 0.264172, "gal"
    elif unit == "gal":
        return value / 0.264172, "L"
    else:
        raise ValueError("Unsupported volume unit")

def main():
    print("Unit Converter: Choose a conversion type")
    print("1. Length (meters ↔ feet)")
    print("2. Weight (kilograms ↔ pounds)")
    print("3. Volume (liters ↔ gallons)")

    try:
        choice = int(input("Enter the number of your choice: "))
        value = float(input("Enter the value to convert: "))
        unit = input("Enter the unit of measurement (m, ft, kg, lbs, L, gal): ").strip().lower()

        if choice == 1:
            result, new_unit = convert_length(value, unit)
        elif choice == 2:
            result, new_unit = convert_weight(value, unit)
        elif choice == 3:
            result, new_unit = convert_volume(value, unit)
        else:
            print("Invalid choice. Please restart and choose a valid option.")
            return

        print(f"Converted value: {result:.2f} {new_unit}")

    except ValueError as e:
        print(f"Error: {e}. Please enter a valid numeric value and unit.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Unit Converter: Choose a conversion type
1. Length (meters ↔ feet)
2. Weight (kilograms ↔ pounds)
3. Volume (liters ↔ gallons)
Enter the number of your choice: 50
Enter the value to convert: 300
Enter the unit of measurement (m, ft, kg, lbs, L, gal): m
Invalid choice. Please restart and choose a valid option.


In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.
    :param numbers: List of numerical values.
    :return: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.
    :param numbers: List of numerical values.
    :return: The average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: The maximum value.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: The minimum value.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter the number of your choice: "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice. Please restart and choose a valid option.")
            return

        print(f"Result: {result}")

    except ValueError:
        print("Error: Please enter only numeric values.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number of your choice: 1
Enter numbers separated by spaces: 5
Result: 5.0


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("Filled Array (3x3) with value 7:\n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(sample_array)
print("Zeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("Ones Like Array:\n", ones_like_array)

# 6. Convert a given list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted Numpy Array:\n", numpy_array)


Empty Array (2x2):
 [[2.3970703e-316 0.0000000e+000]
 [5.9781943e-322 6.0127789e-321]]
All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled Array (3x3) with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array:
 [[0 0 0]
 [0 0 0]]
Ones Like Array:
 [[1 1 1]
 [1 1 1]]
Converted Numpy Array:
 [1 2 3 4]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array Mean:", mean_value)

# 5. Create a 10x10 array with random values and find min/max values
random_matrix = np.random.random((10, 10))
min_value, max_value = random_matrix.min(), random_matrix.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array Mean: 0.6308749875432711
Minimum value in 10x10 array: 0.004658690621357042
Maximum value in 10x10 array: 0.9883791457928308
Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array Mean:", mean_value)

# 5. Create a 10x10 array with random values and find min/max values
random_matrix = np.random.random((10, 10))
min_value, max_value = random_matrix.min(), random_matrix.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

# Problem 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
sum_array = x + y
print("Sum of x and y:\n", sum_array)

# 2. Subtract the two arrays
diff_array = x - y
print("Difference of x and y:\n", diff_array)

# 3. Multiply the array with any integer
multiplied_array = x * 2
print("x multiplied by 2:\n", multiplied_array)

# 4. Find the square of each element of the array
squared_array = x ** 2
print("Square of each element in x:\n", squared_array)

# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along row and v and w along column
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v; If error occurs, explain why
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error in concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D array with shape (2,). To concatenate, their dimensions must match appropriately.")

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array Mean: 0.4639774369698001
Minimum value in 10x10 array: 0.02935733597829726
Maximum value in 10x10 array: 0.9899690648319744
Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Sum of x and y:
 [[ 6  8]
 [10 13]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product o

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array Mean:", mean_value)

# 5. Create a 10x10 array with random values and find min/max values
random_matrix = np.random.random((10, 10))
min_value, max_value = random_matrix.min(), random_matrix.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

# Problem 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
sum_array = x + y
print("Sum of x and y:\n", sum_array)

# 2. Subtract the two arrays
diff_array = x - y
print("Difference of x and y:\n", diff_array)

# 3. Multiply the array with any integer
multiplied_array = x * 2
print("x multiplied by 2:\n", multiplied_array)

# 4. Find the square of each element of the array
squared_array = x ** 2
print("Square of each element in x:\n", squared_array)

# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along row and v and w along column
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v; If error occurs, explain why
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error in concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D array with shape (2,). To concatenate, their dimensions must match appropriately.")

# Problem 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_proof = np.dot(A, A_inv)
print("A * A^-1 (Should be Identity Matrix):\n", identity_proof)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("Matrix AB:\n", AB)
print("Matrix BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("(AB)^T == B^T A^T?", np.array_equal(AB_T, BT_AT))

# Solve system of linear equations using Inverse Method
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])

# Compute inverse and solution
coeff_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_inv, const_matrix)
print("Solution using Inverse Method:\n", solution)

# Solve using np.linalg.solve
solution_solve = np.linalg.solve(coeff_matrix, const_matrix)
print("Solution using np.linalg.solve:\n", solution_solve)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array Mean: 0.5169655233214309
Minimum value in 10x10 array: 0.007215897325488108
Maximum value in 10x10 array: 0.9773774793941851
Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Sum of x and y:
 [[ 6  8]
 [10 13]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product 